### ISSUE TITLE
error 2 

### ISSUE THREAD

**Issue by un-lock-me** [anirudh985/TwitterSentimentAnalysis#4]
when I am running the main in configure it says there is no twitterCredentials,

where I can download this file and what is the purpose of that file/?

**Comment by anirudh985** [comment]
You'll need to create that file with the twiiterCredentials. The file should have the following properties set according to your account
twitter4j.oauth.consumerKey, twitter4j.oauth.consumerSecret, twitter4j.oauth.accessToken, twitter4j.oauth.accessTokenSecret

The tutorial for getting these values can be found by searching on the web. One such link is https://www.slickremix.com/docs/how-to-get-api-keys-and-tokens-for-twitter/

**Comment by un-lock-me** [comment]
thanks for your answer,
how I should create that file, I mean with text file and  just data(format)?

Also when I am running search class there is an error. the error that stops me from working with this good source was this:
may I ask you to have a look on that. your code is really helpful for me.

Exception in thread "main" java.lang.NullPointerException
	at edu.stanford.nlp.neural.rnn.RNNCoreAnnotations.getPredictedClass(RNNCoreAnnotations.java:73)
	at usingNLP.SentimentAnalysisUtils$$anonfun$detectSentiment$1.apply(SentimentAnalysisUtils.scala:41)
	at usingNLP.SentimentAnalysisUtils$$anonfun$detectSentiment$1.apply(SentimentAnalysisUtils.scala:39)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at usingNLP.SentimentAnalysisUtils$.detectSentiment(SentimentAnalysisUtils.scala:39)
	at usingNLP.Search$$anonfun$main$1.apply(Search.scala:19)
	at usingNLP.Search$$anonfun$main$1.apply(Search.scala:18)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at usingNLP.Search$.main(Search.scala:18)
	at usingNLP.Search.main(Search.scala)

Process finished with exit code 1

**Comment by un-lock-me** [comment]
I really need your help,

how you were able to compare corenlp result with naive bayesian,

if there is a way to save the corenlp result in a text like this : sentence sentiment
?
may I ask you to answer please this question
